
ALTER TABLE public.diplomas
  ADD COLUMN IF NOT EXISTS sexe TEXT,
  ADD COLUMN IF NOT EXISTS matricule TEXT,
  ADD COLUMN IF NOT EXISTS jury_session TEXT,
  ADD COLUMN IF NOT EXISTS credits INTEGER,
  ADD COLUMN IF NOT EXISTS grade_letter TEXT,
  ADD COLUMN IF NOT EXISTS director_name TEXT,
  ADD COLUMN IF NOT EXISTS sub_reference TEXT;
